default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix: /
    options: { i18n_prefix: admin }
ajax:
    resource: "@AppBundle/Controller/AjaxController.php"
    type:     annotation
    prefix: /ajax
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options: { i18n: false }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/password
